### ISSUE TITLE
Peer Review - Mac

### ISSUE THREAD

**Issue by NimG98** [OpenLiberty/draft-guide-microprofile-reactive-messaging#15]
Peer Review: review to be done by a peer member. 

Functionality
---
- [x] Check that the guide has working instructions and sample code
- [x] Test the guide on 3 platforms: Mac, Win, Linux
- [x] If any URL visits, try them on different browsers: Firefox, Chrome, Safari
- [ ] If any URL visits, try `curl` command where applicable 

Formatting & Presentation
---
- [x] Check the quality of code according to the best coding practices
    - [ ] Ensure that command substitutions use the `$(cmd)` format and not ``` `cmd` ```
    - [x] Ensure that the console output of the integrated tests do not include the `[INFO]` tab
- [x] Check the quality and presentation of guide according to [Structure and Style Guideline](https://github.com/OpenLiberty/draft-guides-template/wiki/Guidelines-for-Structure-and-Styles)
- [x] Check the consistency of guide with template and other guides
- [x] Examples with the right outcomes are provided
- [x] Example with the wrong outcomes, if any, are provided
- [ ] Check that all licensing statements are properly stated in all files
- [x] Check that the `pom.xml`, `server.xml`, etc files are clean
- [x] Check that the directories are properly structured
- [x] Ensure that the guide is using the latest version of the `liberty-maven-plugin` or `liberty-gradle-plugin` where applicable
- [x] Check that some of these `page-tags` are used in a guide: `MicroProfile, Maven, Docker, Kubernetes, Gradle, Java EE, Security, Cloud`. Only these tags are visible on the website. Latest list [here](https://github.com/OpenLiberty/openliberty.io/blob/master/src/main/content/_includes/visible-tags.liquid). 
- [x] Check the `attribution` statement is accurate for the guide
- [ ] Verify the `travisTest.sh` script, if any, is accurate and consistent with other guides

Peer Testing: tests to be done by a peer member.

Guide’s contributor’s (if available, otherwise peer tester’s) responsibility: 
- [x] Additional tests where applicable: 
    - [x] Define test coverage and review with team (including guide contributor, if available)
    - [x] Define detail test cases 
    - [x] Consider corner cases targeting the specific guide
    - [x] Consider different platform tests, ie, Mac, Windows, Linux
    - [x] Consider corner cases UI tests
    - [x] Consider testing URL on all browsers, ie, FF, Chrome, Safari
    - [ ] Consider testing the `curl` command for URL visits
- [x] Consider building with both Maven and Gradle build tools 
- [x] Testing with different IDEs, ie, Atom, Eclipse (Optional: VS.code, IntelliJ, Microclimate)
- [ ] Run Acrolinx Checker on draft (above 70 score approximately)
- [ ] Consider SEO title and description for the guides 
- [ ] Ensure automated test is enable, set up with Travis CI, and able to schedule tests 
- [x] Run `diff -r start/ finish/` and there's no differences
- [ ] Ensure that the automation tests are able to run when PR is created

Peer Tester’s responsibility: 
- [x] Check the appearance of the guide on test site for the following items: 
    - [x] Table of contents 
    - [x] Headings
    - [x] Paragraphs
    - [x] code snippets
    - [x] outputs
    - [x] links
    - [x] hotspots 
- [x] Test the guide end-to-end with working instruction and sample code
- [x] Perform all the defined test cases

**Comment by NimG98** [comment]
- [ ] guide description sounds weird at the architecture part
    > Learn how to use MicroProfile Reactive Messaging to implement reactive architecture application.
   
     - suggestions:
        - `...to implement an application with a reactive architecture.`
        - `...to implement a reactive application.`

## What you’ll learn

- [ ] Add "Apache" before "Kafka broker"
    > You’ll also learn how to send messages between these microservices using Kafka broker.

    - [ ] also add a link for Kafka broker, or add a description and a link to the docs for Kafka broker in the "What is Kafka?" section

- [ ] This sentence is really long
    > MicroProfile Reactive Messaging provides a way to build systems of microservices advocating responsive, location transparency, elastic, non-blocking, resiliency to failure and temporal decoupling, enforcing asynchronous message passing between the different parts of the system.

    - also some of the words have a different tense.
      `repsonsive`, `elastic`, `non-blocking` don't make sense, make them nouns like 
      `location transparency` 
- [ ] Don't make the whole sentence be a hyperlink, just make the "MicroProfile Reactive Messaging Specification" a hyperlink only
    > See “MicroProfile Reactive Messaging Specification” for more information
    
    - also needs a period at the end of this sentence.
- [ ] is Reactive Architecture supposed to be capitalized here, because in other instances it's lowercase
    > The Restaurant application is designed with Reactive Architecture.
- [ ] Remove "namely", and put ":" instead. Also put a comma after `servingWindow` before `restaurantBFF`.
    > The application that you’ll be working with consists of five microservices namely `order`, `kitchen`, `bar`, `servingWindow` and `restaurantBFF`.
- [ ] Don't start the sentence with "And"
    > And uses Kafka broker to enable reactive messaging communication between the Producer and Consumer microservices over the messaging channels.
- [ ] should the picture say "message", not "massage"
    ![image](https://user-images.githubusercontent.com/46586499/75168808-7d74bc00-56f5-11ea-9922-0702b79c53ba.png)

    - [ ] also sometimes in the picture it says "ready2serve" or "ready2-serve". Use one consistently.
- [ ] "ready to serve" should be "ready-to-serve"
    > The `servingWindow` microservice contains a list of all ready to serve food and beverages. 
- [ ] add a "the" before `kitchen`
    > It consumes these statuses from `kitchen` and `bar` microservices. 

## Additional prerequisites
- [ ] either this section isn't needed or you need to adjust later paragraphs. 
    - Other guides like the [async guide](https://openliberty.io/guides/microprofile-rest-client-async.html#building-and-running-the-application) only need Docker and don't have additional prereqs. 
    - This section is almost identical to the paragraph in the "Building the application" section
    ![image](https://user-images.githubusercontent.com/46586499/75169857-3daed400-56f7-11ea-8af8-921d63df057f.png)
    ![image](https://user-images.githubusercontent.com/46586499/75169801-2c65c780-56f7-11ea-91e1-d168efcfe9ca.png)

## Creating a Reactive Messaging application
- [ ] add "the" after "on"
    > MicroProfile Reactive Messaging recommends a design to build reactive applications based on following main concepts:
- [ ] remove extra space after "channel"
    > Reactive messaging uses Connectors to attach one end of a channel  and are configured using MicroProfile Config. 
    - [ ] also attach one end of a channel to what? Like what is it being attached to.
- [ ] remove this sentence
    > Most of the code is already provided for use.
- [ ] Add comma after `bar`. Add "a" before `microprofile-config.properties`, and change "contains" to "contain".
    > Each of the four microservices `order`, `kitchen`, `bar` and `servingWindow` contains `microprofile-config.properties` file,
- [ ] this sentence was just repeated only a few sentences ago. Remove one of them.
    > `Open Liberty` includes the `liberty-kafka` connector for sending and receiving messages from an Apache Kafka broker.
    - [ ] Also `Open Liberty` should not have the backticks and should just be Open Liberty

**Comment by NimG98** [comment]
## Additional prerequisites
- [ ] either this section isn't needed or you need to adjust later paragraphs. 
    - Other guides like the [async guide](https://openliberty.io/guides/microprofile-rest-client-async.html#building-and-running-the-application) only need Docker and don't have additional prereqs. 
    - This section is almost identical to the paragraph in the "Building the application" section
    ![image](https://user-images.githubusercontent.com/46586499/75169857-3daed400-56f7-11ea-8af8-921d63df057f.png)
    ![image](https://user-images.githubusercontent.com/46586499/75169801-2c65c780-56f7-11ea-91e1-d168efcfe9ca.png)

**Comment by NimG98** [comment]
## Creating a Reactive Messaging application
- [ ] add "the" after "on"
    > MicroProfile Reactive Messaging recommends a design to build reactive applications based on following main concepts:
- [ ] remove extra space after "channel"
    > Reactive messaging uses Connectors to attach one end of a channel  and are configured using MicroProfile Config. 
    - [ ] also attach one end of a channel to what? Like what is it being attached to.

### Configuring the MicroProfile Reactive Messaging

- [ ] remove this sentence
    > Most of the code is already provided for use.
- [ ] Add comma after `bar`. Add "a" before `microprofile-config.properties`, and change "contains" to "contain".
    > Each of the four microservices `order`, `kitchen`, `bar` and `servingWindow` contains `microprofile-config.properties` file,
- [ ] this sentence was just repeated only a few sentences ago. Remove one of them.
    > `Open Liberty` includes the `liberty-kafka` connector for sending and receiving messages from an Apache Kafka broker.
    - [ ] Also `Open Liberty` should not have the backticks and should just be Open Liberty

- [ ] Remove extra space before period
    > Create the microprofile-config.properties file .
- [ ] `mp.messaging.connector.liberty-kafka.bootstrap.servers`, `food`, `beverage`, `updateStatus` hotspots should highlight just that one line of code, not the comment too
- [ ] What do you mean by understood, can you please make it more clear
    > All those properties should be understood by the Apache Kafka client API.
- [ ] change "Rest all" to "The rest of"
    > Rest all the microservices use similar `microprofile-config.properties` configuration.

### Building the order microservice
- [ ] add a word after `POST` like "request" or something
    > The `order` microservice creates Orders when the `POST` of the endpoint `/orders` is called.
- [ ] I think the code being highlighted on the code pane for the `/orders` hotspot should be put on the word `POST` instead. 
    - Isn't what's being highlighted better represent the `POST` word then `/orders`, since we are trying to highlight only the POST section of the code, and since `/orders` is technically represented by the entire file. 
- [ ] `createOrder()` hotspot should only highlight the method without the annotations
- [ ] `Queue` hotspot doesn't need to highlight `break;` statement
- [ ] remove `LinkedBlockingQueue` from the second sentence. Put it in the first sentence, replacing `Queue` to  `LinkedBlockingQueue`
    > The `createOrder()` method receives `food` or `beverage` Orders and adds it to the respective `Queue`. As soon as an Order is added to the Queue, LinkedBlockingQueue `take()` retrieves and removes the Orders. 

    - [ ] also LinkedBlockingQueue should be with backticks -> `LinkedBlockingQueue`
    - [ ] change "`take()`" to "the `take()` method"
- [ ] separate "ReactiveMessaging" into two words
    > The ReactiveMessaging implementation generates Reactive Streams for those Orders and publishes it to Kafka over `@Outgoing("food")` or `@Outgoing("beverage")` channels, which we configured previously in `microprofile-config.properties` `food` or `beverage` stream. 
    - [ ] add "the" before `microprofile-config.properties`
    - [ ] add file hotspot pointing to codepane for `microprofile-config.properties`
- [ ] "it's" should be without apostrophe ("its")
    > The `@Incoming("updateStatus")` channel with it’s properties defined in `microprofile-config.properties` receives an updated Order statuses from the Kafka which is being sent by `kitchen` or `bar` microservices.
    - [ ] also change `microprofile-config.properties` to "the `microprofile-config.properties`file"
    - [ ] remove "an"
    - [ ] I think there's a missing word after Kafka ("from the Kafka [insert missing word here?]").
           Or just "from Kafka"
- [ ] Do you mean Replace?
    > "Read the Maven configuration file"
    - [ ] if you actually want them to read it, there's no need for the blockhead arrow saying "Read the Maven configuration file". Just have a sentence talking about that file
     - [ ] if you meant Replace, then "Replace the Maven configuration file" would need a period at the end
- [ ] "maven" should be capitalized to "Maven"
    > In order to develop the MicroProfile Reactive Messaging application using maven, add the `microprofile-reactive-messaging-api` and `kafka-clients` dependencies to the pom.xml. 
     - [ ] by saying "add the ... ", it makes it sound like you want the user to add those dependencies, even though it's already added for them in their start pom.xml. Change the wording of that sentence a bit.
    - [ ] `pom.xml` should be file hotspot pointing to `pom.xml` file in codepane

### Building the Other microservices
- [ ] In the title of this subsection, change "Other" to lowercase "other"
- [ ] or instead of dividing this "other microservices" into three subsections, make these sections at the same level as the "order" microservice section
- [ ] Add "The" at the beginning of this sentence.
    > `kitchen`, `bar` and `servingWindow` microservices are put together in this section.
- [ ] don't need subsections ("Building the kitchen microservice", "Building the bar microservice", etc.) since they don't appear in the table of contents, and the sections are really small anyways
- [ ] when you have a hotspot for Incoming/Outgoing channels, most of the time you highlight the entire method and it's Incoming/Outgoing annotation. But in this sentence, the hotspot only highlights the annotation. Make the hotspot for channels consistent.
    > If the order is a food, `kitchen` service receives an Order on `@Incoming("foodOrderConsume")` channel, processes it in `initFoodOrder()` method and sends back `IN_PROGRESS` status on `@Outgoing("foodOrderPublishIntermediate")` and `READY` status on `@Outgoing("foodOrderPublish")` to Kafka over MicroProfile Reactive Messaging channels.
    - [ ] add "an" before `IN_PROGRESS`, and add "a" before `READY`
    - [ ] add "the" after "on" and before `@Incoming("foodOrderConsume")`
    - [ ] add "channel" after `@Outgoing("foodOrderPublishIntermediate")`, and also after `@Outgoing("foodOrderPublish")`. Also add "the" before "on" here.
- [ ] same thing above applies to the following sentence
    > If the order is a drink, `bar` service receives an Order on `@Incoming("bevOrderConsume")` channel, processes it in `initBeverageOrder()` method and sends back `IN_PROGRESS` status on `@Outgoing("bevOrderPublishInter")` and `READY` status on `@Outgoing("beverageOrderPublish")` to Kafka over MicroProfile Reactive Messaging channels.
- [ ] just say "channel" now instead of "MicroProfile Reactive Messaging channel"
     > `servingWindow` microservice receives the `Ready` Order from the `bar` and `kitchen` microservices over `@Incoming("orderReady")` MicroProfile Reactive Messaging channel. Once the Order is served, it’s marked as `COMPLETED` and the status is sent across to `order` microservice using the `@Outgoing("completedOrder")` MicroProfile Reactive Messaging channel.
    - [ ] add "The" at the start of the sentence
    - [ ] add "the" before `@Incoming("orderReady")`
    - [ ] add "the" before `order` microservice

**Comment by NimG98** [comment]
## Configuring the server
- [ ] add a period at the end of this sentence
    > Configure the server to enable MicroProfile Reactive Messaging by adding `mpReactiveMessaging-1.0` `feature` element to the `server.xml`. 
    - [ ] `feature` should not have backticks and should just be a normal word
    - [ ] make `server.xml` a file hotspot pointing to the `server.xml` in the codepane
- [ ] Change "Rest all" to "The rest of"
    > Rest all the microservices have `server.xml` already configured.
     - [ ] make `server.xml` a file hotspot pointing to the `server.xml` in the codepane

**Comment by NimG98** [comment]
## Trying the application
- [ ] Remove the comma after "After"
    > After, waiting for a while to get the application completely started, you can access the application by making requests to the `restaurantBFF` endpoint using OpenAPI.
- [ ] don't need the "Place Orders" and other subtitles
- Change this sentence:
    > Expand the /api/orders POST request to post an Order and click Try it out. Copy the following example input into the text box:

    To:
    > Make a `POST` request to the `/api/orders` endpoint. To make this request, expand the `POST` endpoint on the UI, click the `Try it out` button. Copy the following example input into the text box, and then click the `Execute` button. The `POST` request adds a [say what doing this request does].

- [ ] Change this sentence:
    > Now Expand the `/api/orders` `GET` request to get the Order status and click Try it out.
Click `Execute` and you will see the response with `IN_PROGRESS` status.

   To: 
   > Next, make a `GET` request to the `/api/orders` endpoint. To make this request, expand the `GET` endpoint on the UI, click the `Try it out button`, and then click the `Execute` button. The `GET` request returns information about the orders. The response shows that the orders have an `IN_PROGRESS` status.
- [ ] These two green command boxes are supposed to show output, so they should be gray boxes instead of the copyable green boxes
    ![image](https://user-images.githubusercontent.com/46586499/75189192-af991480-571b-11ea-9c21-ac4148e122d4.png)
- [ ] add "a" before `READY`
    > Click `Execute` again and you will see the response with `READY` status.
- [ ] This section needs to explain more of what's happening
    ![image](https://user-images.githubusercontent.com/46586499/75189649-9f356980-571c-11ea-896e-3babcdfbb128.png)
    - Change to:
        > Make a `POST` request to the `/api/servingWindow/{orderId}` endpoint to complete an Order. Expand the `POST` endpoint on the UI, click the `Try it out` button. Copy the following order ID into the text box, and then click the `Execute` button. [Put sentence here explaining what this did, i.e. make the order 0002 change from READY to COMPLETED, etc.]
- [ ] Change this:
    > Now Expand the `/api/orders` `GET` request to get the Order status and click Try it out.
    > 
    > Click `Execute` and you will see the response with `COMPLETED` status for `orderId 0002`. This updated status is cascaded to the order microservice. 

    To:
    > Then, make a `GET` request to the `/api/orders` endpoint again and verify that the status for the order with an `orderID` of `0002` is now labelled as `COMPLETED`. 
- [ ] the green command box is supposed to show output, so it should be a gray box instead
    ![image](https://user-images.githubusercontent.com/46586499/75190397-33540080-571e-11ea-99ac-71088f5b4ae3.png)

**Comment by NimG98** [comment]
## Tearing down the environment
 - [ ] Is this line needed? When did the users have to leave the start directory
    > Navigate back to the `start` directory.

**Comment by NimG98** [comment]
### diff -rq finish start
- [ ] `finish/bar/src/main/java/io/openliberty/guides/bar/BarResource.java` 
    - [ ] `return Response.ok().entity("The bar service is running...\n" ` line has extra space at the end, and the file in the start directory does not.
    - [ ] has extra blank line on lines 93-94

**Comment by NimG98** [comment]
- [ ] make sure to add this guide in the [guide_tags.json](https://github.com/OpenLiberty/guides-common/blob/master/guide_tags.json) file with the tags corresponding to your
`:page-tags: ['MicroProfile', 'Jakarta EE', 'Microservices']`

**Comment by NimG98** [comment]
Change Dockerfiles:
- [ ] use `FROM openliberty/open-liberty:kernel-java8-openj9-ubi` instead
- [ ] say `Your Name` instead of `My Name`

**Comment by NimG98** [comment]
- [ ] `artifact-id` in `pom.xml` should be the guide-name (`guide-microprofile-reactive-messaging`), not `guide-restaurant`

**Comment by NimG98** [comment]
- [ ] link guide to travis
- [ ] add guide to draft automation tests

**Comment by ankitagrawa** [comment]
addressed
