### ISSUE TITLE
Comments on queries or suggested improvments for instructions

### ISSUE THREAD

**Issue by GraceJansen** [OpenLiberty/draft-guide-microprofile-reactive-messaging#28]
I have put the original text from the guide on the left of the arrow and any comments or queries or suggestions on the right. Hope this is helpful.

•	Temporal decoupling of services in a microservice-based architecture could be achieved using asynchronous communication --> I would maybe change this to can rather than could
•	MicroProfile Reactive Messaging provides a way to build systems of microservices advocating responsiveness, location transparency, elasticity, resiliency to failure and temporal decoupling --> this sentence is misleading, it is written to suggest that reactive messaging achieves the above, but reactive messaging by itself I don’t believe achieves all of the above (e.g. resiliency and responsiveness). If the word advocacy refers to “helping to build a system that achieves this” then I think this is true, but if advocating refers to “achieves the above by itself” then I think we need to rethink. Not entirely clear from that wording. Check guide proves these claims! In the microprofile spec it says the following: “The role of the MicroProfile Reactive Messaging specification is to deliver a way to build systems of microservices promoting both location transparency and temporal decoupling, enforcing asynchronous communication between the different parts of the system.”
•	The OpenLiberty Cafe application is designed with reactive architecture --> is it designed with reactive architecture? Does it comply with the reactive manifesto? Or should this be programming rather than architecture?
•	which configures Kafka connector with the MicroProfile Reactive Messaging channels. --> should this have a “the” before Kafka connector?
•	The group.id defines an unique name --> this should be “a” instead of “an”
•	All these properties should be accepted by the Apache Kafka client API. --> can this be “is accepted” rather than “should be”, it just sounds a little unsure at the moment
•	updated order statuses from the Kafka topic which is being sent by Kitchen or Bar microservices. --> “by the Kitchen or Bar microservices”
•	If the order is a food --> “if the order is an item of food”
•	Kitchen service receives an order --> “received the order”, is this not referring to the order previously mentioned in the sentence?
•	served, it’s marked as --> it is rather than it’s
•	You will build and run the  --> maybe “you will now build…”?
•	Why is “foodOrderPublishIntermediate” named with the full intermediate name but “bevOrderPublishInter” doesn’t? And why is “bevOrderPublishInter” not named with the full beverage name like “beverageOrderPublish”. This seems inconsistent to me.

**Comment by ankitagrawa** [comment]
> •	Temporal decoupling of services in a microservice-based architecture could be achieved using asynchronous communication --> I would maybe change this to can rather than could

done


> •	MicroProfile Reactive Messaging provides a way to build systems of microservices advocating responsiveness, location transparency, elasticity, resiliency to failure and temporal decoupling --> this sentence is misleading, it is written to suggest that reactive messaging achieves the above, but reactive messaging by itself I don’t believe achieves all of the above (e.g. resiliency and responsiveness). If the word advocacy refers to “helping to build a system that achieves this” then I think this is true, but if advocating refers to “achieves the above by itself” then I think we need to rethink. Not entirely clear from that wording. Check guide proves these claims! In the microprofile spec it says the following: “The role of the MicroProfile Reactive Messaging specification is to deliver a way to build systems of microservices promoting both location transparency and temporal decoupling, enforcing asynchronous communication between the different parts of the system.”

Here advocacy refers to “helping to build a system that achieves this”.

> •	The OpenLiberty Cafe application is designed with reactive architecture --> is it designed with reactive architecture? Does it comply with the reactive manifesto? Or should this be programming rather than architecture?

I think it's architecture. Because we are containerizing the micro services and if we deploy those on Kube clusters it would resemble that.

> •	which configures Kafka connector with the MicroProfile Reactive Messaging channels. --> should this have a “the” before Kafka connector?

done

> •	The group.id defines an unique name --> this should be “a” instead of “an”

done

> •	All these properties should be accepted by the Apache Kafka client API. --> can this be “is accepted” rather than “should be”, it just sounds a little unsure at the moment

I changed it to All these properties are required by the...

> •	updated order statuses from the Kafka topic which is being sent by Kitchen or Bar microservices. --> “by the Kitchen or Bar microservices”

done

> •	If the order is a food --> “if the order is an item of food”

done

> •	Kitchen service receives an order --> “received the order”, is this not referring to the order previously mentioned in the sentence?

Yes it is. But we are trying to setup a flow here.  We are telling the user that kitchen services receives and order and then processes it.. I am not very sure but I guess usually I have seen guides to be more in present tense as compared to the past tense.

> •	served, it’s marked as --> it is rather than it’s

done

> •	You will build and run the  --> maybe “you will now build…”?

done

> •	Why is “foodOrderPublishIntermediate” named with the full intermediate name but “bevOrderPublishInter” doesn’t? And why is “bevOrderPublishInter” not named with the full beverage name like “beverageOrderPublish”. This seems inconsistent to me.

because beverageOrderPublishIntermediate seems like a very long name

**Comment by ankitagrawa** [comment]
The application has been changed to System-Inventory and these points don't hold. Closing this issue for now.
