### ISSUE TITLE
Suggestions to improve microservice decomposition

### ISSUE THREAD

**Issue by matthewpwilson** [OpenLiberty/draft-guide-microprofile-reactive-messaging#29]
Reading the sample guide, I'm wondering if the set of 5 microserivces could be improved.   I'm not convinced they all add value at the moment, and the present quite a complicated architecture for the reader to get their head around. 

For example, the Kitchen and Bar services are very similar, are both needed? 
Why separate the Order service from OpenLibertyCafe? 

I think the example could also demonstrate more benefits of reactive/event-driven architecture. For example, you could have a Stockroom service that consumes the Order events, maintains stock levels for each product and places an order with a 'supplier' if levels run low.  This shows the ability to easy add another service acting on the order data without the Order or Kitchen services being changed. 

I understand a follow-on guide will demonstrate 'pushing' order status to a client, this will also be great example of event advantage.

**Comment by ankitagrawa** [comment]
@gkwan-ibm FYI

**Comment by ankitagrawa** [comment]
The application has been changed to System-Inventory and these points don't hold. Closing this issue for now.
