### ISSUE TITLE
Using generate to take from a BlockingList doesn't demonstrate reactive well

### ISSUE THREAD

**Issue by Azquelt** [OpenLiberty/draft-guide-microprofile-reactive-messaging#35]
In the guide, you've used this pattern quite a lot to bridge between the reactive messaging and REST based parts of the application:

```
private BlockingQueue<Order> queue = new LinkedBlockingQueue<>();

@Outgoing("myChannel")
private PublisherBuilder<Order> sendOrders() {
    return ReactiveStreams.generate(() -> queue.take());
}

@POST
public Response recieveOrder(Order theOrder) {
    queue.add(theOrder);
}
```

This pattern isn't great because it calls `queue.take()` within the argument to `generate()`, which means that there will always be a thread which is just waiting for the next thing to be put onto the queue.

Unfortunately, neither MP Reactive Messaging, nor MP Reative Streams Operators provide a good way of bridging between the reactive and non-reactive parts of a program right now. (Hopefully Reactive Messaging will add `Emitter` to do this task in a future version.)

For now, we could either write a better piece of custom bridging logic (and ideally reuse it between the services), or pull in another reactive library like RxJava and use [Flowable.create()][flowable-create] to make the bridge.

[flowable-create]: http://reactivex.io/RxJava/3.x/javadoc/io/reactivex/rxjava3/core/Flowable.html#create-io.reactivex.rxjava3.core.FlowableOnSubscribe-io.reactivex.rxjava3.core.BackpressureStrategy-

**Comment by Azquelt** [comment]
It may also be the case that for some parts of the guide, it might be easier to call the Kafka APIs directly, but that's more a reflection on Reactive Messaging rather than on the guide.

**Comment by ankitagrawa** [comment]
> In the guide, you've used this pattern quite a lot to bridge between the reactive messaging and REST based parts of the application:
> 
> private BlockingQueue<Order> queue = new LinkedBlockingQueue<>();
> 
> @Outgoing("myChannel")
> private PublisherBuilder<Order> sendOrders() {
>     return ReactiveStreams.generate(() -> queue.take());
> }
> 
> @POST
> public Response recieveOrder(Order theOrder) {
>     queue.add(theOrder);
> }
> This pattern isn't great because it calls queue.take() within the argument to generate(), which means that there will always be a thread which is just waiting for the next thing to be put onto the queue.
> 
> Unfortunately, neither MP Reactive Messaging, nor MP Reative Streams Operators provide a good way of bridging between the reactive and non-reactive parts of a program right now. (Hopefully Reactive Messaging will add Emitter to do this task in a future version.)
> 
> For now, we could either write a better piece of custom bridging logic (and ideally reuse it between the services), or pull in another reactive library like RxJava and use Flowable.create() to make the bridge.

Nice suggestion.
Do you have any examples or suggestions on how to achieve this? 

We built this based on what we understand so far.

**Comment by ankitagrawa** [comment]
> It may also be the case that for some parts of the guide, it might be easier to call the Kafka APIs directly, but that's more a reflection on Reactive Messaging rather than on the guide.

ok. I guess since the focus of this guide is reactive messaging. Do we need to address it? If yes where do you think we should use Kafka API's?

**Comment by ankitagrawa** [comment]
@Azquelt

**Comment by yeekangc** [comment]
If Emitter is there in SmallRye, is that something we can use?  Otherwise, I am open for us to consider pulling another library for now.  A common custom logic can work too and we can replace that later.

**Comment by Azquelt** [comment]
We don't expose the smallrye APIs to applications, so you can't just use `Emitter` in your code, unfortunately. (This is consistent with other features which don't expose non-spec APIs.)

You can disable the mpReactiveMessaging feature and package the smallrye library as an app, but that's probably not something we want to guide users towards.

I'll put together an example using RxJava since that's probably the nicest way to do it and it can serve as an example of how to use other reactive libraries with MP Reactive Messaging.

**Comment by Azquelt** [comment]
Here's an example of bridging from JAX-RS to reactive messaging using rxJava

```
import io.reactivex.rxjava3.core.BackpressureStrategy;
import io.reactivex.rxjava3.core.Flowable;
import io.reactivex.rxjava3.core.FlowableEmitter;

@ApplicationScoped
@Path("/message")
public class MyResource {
    
    private FlowableEmitter<String> receivedMessageSink;
    
    @Outgoing("receivedMessages")
    public Publisher<String> receivedMessages() {
        Flowable<String> flowable = Flowable.<String>create(emitter -> this.receivedMessageSink = emitter, BackpressureStrategy.BUFFER);
        return flowable;
    }
    
    @POST
    public Response postMessage(String message) {
        receivedMessageSink.onNext(message);
        return Response.ok().build();
    }
}
```

Just one note on this: bridging between something non-reactive to something reactive has an inherent problem. Reactive Messaging has backpresure, while JAX-RS does not.

If reactive messaging isn't ready to receive a message but JAX-RS wants to send one, you need to decide what should happen. Sensible strategies here are probably to either throw an exception, or to allow messages to be stored in a list in memory until they can be processed.

Since your app is just sending messages on to Kafka which should be very quick, I've opted for the second option here, messages will be buffered until they're ready to be received.

**Comment by ankitagrawa** [comment]
@Azquelt Thanks for the snippet. Will try it out and let you know how it goes.

**Comment by ankitagrawa** [comment]
The application has been changed to System-Inventory and these points don't hold. Closing this issue for now.
