### ISSUE TITLE
Processing of orders by Bar and Kitchen is slightly odd

### ISSUE THREAD

**Issue by Azquelt** [OpenLiberty/draft-guide-microprofile-reactive-messaging#36]
These methods look odd to me:

```
    @Incoming("beverageOrderConsume")
    @Outgoing("beverageOrderPublishStatus")
    public CompletionStage<Order> initBeverageOrder(Order newOrder) {
        logger.info("Order " + newOrder.getOrderId() + " received as NEW");
        logger.info(newOrder.toString());
        return prepareOrder(newOrder);
    }

    @Outgoing("beverageOrderPublishStatus")
    public PublisherBuilder<Order> sendReadyOrder() {
        return ReactiveStreams.generate(() -> {
            try {
                Order order = inProgress.take();
                prepare(5);
                order.setStatus(Status.READY);
                logger.info("Order " + order.getOrderId() + " is READY");
                logger.info(order.toString());
                return order;
            } catch (InterruptedException e) {
                e.printStackTrace();
                return null;
            }
        });
    }

    private CompletionStage<Order> prepareOrder(Order order) {
        return CompletableFuture.supplyAsync(() -> {
            prepare(10);
            Order inProgressOrder = order.setStatus(Status.IN_PROGRESS);
            logger.info("Order " + order.getOrderId() + " is IN PROGRESS");
            logger.info(order.toString());
            inProgress.add(inProgressOrder);
            return inProgressOrder;
        }, executor);
    }
```

It looks like the code does this:
 - receive an Order
 - on another thread, sleep for 10 seconds+ to simulate preparing, then send a message to say the order is `IN_PROGRESS` and add it to the `inProgress` queue
   - despite doing this work on another thread using `supplyAsync` we still won't process another order until we reach this point
 - then `prepareOrder` will take it off the `inProgress` thread, sleep for 5+ seconds to simulate more preparing and then send a message to say the order is `READY`

It's not clear what the intent is here, why `prepareOrder` uses `supplyAsync` or why the code simulates `prepare()`ing the order in two different places.

**Comment by ankitagrawa** [comment]
@Azquelt 
> It's not clear what the intent is here, why prepareOrder uses supplyAsync or why the code simulates prepare()ing the order in two different places.

- Technically IN_PROGRESS and READY status code would run in parallel after prepareOrder() code adds it to the queue `inProgress.add(inProgressOrder);`.
- The intent is to show users different Orders statuses and how reactive messaging can be used to achieve that. Also we are trying to mimic real world scenario as closely as we can.

**Comment by Azquelt** [comment]
Please describe the order of events which are meant to occur when the kitchen service receives an order.

E.g.
* Kitchen receives order
* Kitchen sends message to say that the order is in progress
* Kitchen does some work to prepare the meal
* Kitchen sends message to say that the order is ready

Please also indicate if any of the steps should be run in parallel for a single order

Please also indicate whether multiple orders should be processed in parallel.

**Comment by ankitagrawa** [comment]
> Please describe the order of events which are meant to occur when the kitchen service receives an order.
> 
> E.g.
> 
> Kitchen receives order
> Kitchen sends message to say that the order is in progress
> Kitchen does some work to prepare the meal
> Kitchen sends message to say that the order is ready
> Please also indicate if any of the steps should be run in parallel for a single order

Once the kitchen receives an order it should be execute in_progress and ready in parallel so that it can cater to other orders.

> Please also indicate whether multiple orders should be processed in parallel.
Yes multiple orders are actually processed in parallel. We have seen that happening in logs.

**Comment by Azquelt** [comment]
> Once the kitchen receives an order it should execute in_progress and ready in parallel so that it can cater to other orders.

Sorry, I don't understand what you've written here. You've put "it should execute in_progress and ready", but I'm not sure what that means?

I also still have the following questions:
* When should it send the IN_PROGRESS status message?
* When should it send the READY status message?
* Is it at some point supposed to wait and pretend to be doing "work"?

Please list out the order in which these actions should occur.

> Yes multiple orders are actually processed in parallel. We have seen that in logs.

I didn't ask what it actually does, I asked what it's _meant_ to do.

The code as written doesn't make much sense to me, I'm trying to understand what you are trying to do.

**Comment by Azquelt** [comment]
We discussed this on a call.

The desired order of operations is:
* Receive order
* sleep
* send IN_PROGRESS status message
* asynchronously, while starting processing of the next message:
  * sleep again
  * send READY status message

The key point for me is that it looks like the asynchronicity is accomplished by the call to `CompletableFuture.supplyAsync`, but this is not actually the case.

We came up with this revised code which avoids giving that impression:

```java
@ApplicationScoped
@Path("/beverageMessaging")
public class BarResource {

	private static Logger logger = Logger.getLogger(BarResource.class.getName());

	private Executor executor = Executors.newSingleThreadExecutor();
	private BlockingQueue<Order> ready = new LinkedBlockingQueue<>();
	private Random random = new Random();

	@GET
	@Produces(MediaType.TEXT_PLAIN)
	public Response getStatus() {
		return Response.ok().entity("The bar service is running...\n" + ready.size() + " orders in the queue.").build();
	}

	// tag::bevOrderConsume[]
	@Incoming("beverageOrderConsume")
	// end::bevOrderConsume[]
	// tag::bevOrderPublishInter[]
	@Outgoing("beverageOrderPublishStatus")
	// end::bevOrderPublishInter[]
	// tag::initBevOrder[]
	public Order initBeverageOrder(Order newOrder) {
		logger.info("Order " + newOrder.getOrderId() + " received as NEW");
		logger.info(newOrder.toString());
		Order order = prepareOrder(newOrder);
		executor.execute(() -> {
			try {
				prepare(5);
				order.setStatus(Status.READY);
				logger.info("Order " + order.getOrderId() + " is READY");
				logger.info(order.toString());
				ready.put(order);
			} catch (InterruptedException e) {
				e.printStackTrace();
			}
		});
		return order;
	}
	// end::initBevOrder[]

	// tag::bevOrder[]
	@Outgoing("beverageOrderPublishStatus")
	// end::bevOrder[]
	public PublisherBuilder<Order> sendReadyOrder() {
		return ReactiveStreams.generate(() -> {
			try {
				Order order = ready.take();
				return order;
			} catch (InterruptedException e) {
				e.printStackTrace();
				return null;
			}
		});
	}

	private Order prepareOrder(Order order) {
			prepare(10);
			Order inProgressOrder = order.setStatus(Status.IN_PROGRESS);
			logger.info("Order " + order.getOrderId() + " is IN PROGRESS");
			logger.info(order.toString());
			return inProgressOrder;
	}

	private void prepare(int sleepTime) {
		try {
			Thread.sleep((random.nextInt(5) + sleepTime) * 1000);
		} catch (InterruptedException e) {
			Thread.currentThread().interrupt();
		}
	}
}
```

**Comment by ankitagrawa** [comment]
The application has been changed to System-Inventory and these points don't hold. Closing this issue for now.
