### ISSUE TITLE
Application architecture stops just short of using one queue and relying just on status updates

### ISSUE THREAD

**Issue by Azquelt** [OpenLiberty/draft-guide-microprofile-reactive-messaging#37]
When orders are delivered to the system, they are published to the `food` and `beverage` topics and also to the status topic.

However, after the bar and kitchen have processed these orders, they send them back only using the `status` topic.

It would be possible to do away with the `food` and `beverage` topics altogether by having the bar and kitchen just look for `NEW` status updates.

**Comment by ankitagrawa** [comment]
> When orders are delivered to the system, they are published to the food and beverage topics and also to the status topic.
@Azquelt 
> 
> However, after the bar and kitchen have processed these orders, they send them back only using the status topic.
> 
> It would be possible to do away with the food and beverage topics altogether by having the bar and kitchen just look for NEW status updates.

- While that's correct we don't wanna over complicate things for the users. Having different topic simplifies that.
- Also we don't want other microservices to get messages which are not useful for them. For ex new order as per your suggestion will go to all the microservices bcoz all of them will have @Incoming annotation. We don't want Bar to get message if it's a food.

**Comment by Azquelt** [comment]
ok
