### ISSUE TITLE
If scaled, the application provides no guarantee that status messages appear in order

### ISSUE THREAD

**Issue by Azquelt** [OpenLiberty/draft-guide-microprofile-reactive-messaging#38]
This is more a comment than an issue, but at the moment if you were use more than one partition for the status topic there's no guarantee that the status updates will appear in order.

Kafka only guarantees that messages are processed in order within the same partition, so you'd want to ensure that all messages about the same order end up in the same partition.

I think this can be done by setting the orderId as a key in each message and configuring kafka to distribute messages to partitions based on the key.

**Comment by ankitagrawa** [comment]
Good suggestion but the application itself is complicated. We only want to introduce reactive-messaging to users using this guide. Adding more Kafka related config would make it even harder to understand the concept. We have another guide to talk about Kafka in the pipeline.

**Comment by Azquelt** [comment]
Agree that this can be out of scope for this guide.
