### ISSUE TITLE
How does the application cope with an outage?

### ISSUE THREAD

**Issue by Azquelt** [OpenLiberty/draft-guide-microprofile-reactive-messaging#39]
If one of the microservices fails, will orders be lost?

Currently, I think that if either the Kitchen or Bar crashed, some orders would be lost.

**To make sure orders are not lost, you must ensure that a `Message` is not acknowledged until the processing of it is complete.**

By "complete" I mean that any output from processing has been stored in a durable store which will survive an outage. Usually this means that a message has been sent to the Kafka broker and it has acknowledged the message.

In addition, when you receive an order, you probably don't want to send the REST response until the created message has been acknowledged so that you can send an error back if for some reason you can't store the order.

**Comment by ankitagrawa** [comment]
> If one of the microservices fails, will orders be lost?
Nope unless the Microservice fails after message is acknowledged.

> Currently, I think that if either the Kitchen or Bar crashed, some orders would be lost.

I guess the default acknowledgement strategy is POST_PROCESSING. We have another guide that talks about Manual acknowledgement strategy and we can explain these difference there.

> By "complete" I mean that any output from processing has been stored in a durable store which will survive an outage. Usually this means that a message has been sent to the Kafka broker and it has acknowledged the message.
> 
> In addition, when you receive an order, you probably don't want to send the REST response until the created message has been acknowledged so that you can send an error back if for some reason you can't store the order.
While the application might not be 100% reactive we are trying to keep it as simple as possible and 
introduce the reactive messaging concept to the users. Using Kafka API's to check if the message has been acknowledged or not adds another level of complexity to the code.

@Azquelt

**Comment by Azquelt** [comment]
> I guess the default acknowledgement strategy is POST_PROCESSING.

The default acknowledgement strategy varies depending on what method signature is used. See the table here: https://download.eclipse.org/microprofile/microprofile-reactive-messaging-1.0/microprofile-reactive-messaging-spec.html#_message_acknowledgement

In addition, you're putting messages in and out of the reactive system, e.g. you use a method with just `@Incoming`, put the object on a queue and return. As far as reactive messaging is concerned, when the method returns, the processing is done, so even if the acknowledgement strategy is `POST_PROCESSING`, your message will still be acknowledged while it's on the queue, rather than after it's been fully processed.

>  While the application might not be 100% reactive we are trying to keep it as simple as possible and introduce the reactive messaging concept to the users. Using Kafka API's to check if the message has been acknowledged or not adds another level of complexity to the code.

Message acknowledgement is a reactive messaging concept, not a Kafka API. The kafka connector handles talking to kafka for you and acknowledges the message after the kafka broker has received and stored it.

**Comment by ankitagrawa** [comment]
> In addition, when you receive an order, you probably don't want to send the REST response until the created message has been acknowledged so that you can send an error back if for some reason you can't store the order.

How would you achieve this with Outgoing annotation? Don't u need some Kakfa API to check the offset value to make sure that the message in acknowledged? 

> While the application might not be 100% reactive we are trying to keep it as simple as possible and introduce the reactive messaging concept to the users. Using Kafka API's to check if the message has been acknowledged or not adds another level of complexity to the code.

I replied this for the above point where in you ask us to send response only after message is acknowledged.

**Comment by ankitagrawa** [comment]
> The default acknowledgement strategy varies depending on what method signature is used. See the table here: https://download.eclipse.org/microprofile/microprofile-reactive-messaging-1.0/microprofile-reactive-messaging-spec.html#_message_acknowledgement

Yes I said Post_processing based on the table.
> 
> In addition, you're putting messages in and out of the reactive system, e.g. you use a method with just @Incoming, put the object on a queue and return. As far as reactive messaging is concerned, when the method returns, the processing is done, so even if the acknowledgement strategy is POST_PROCESSING, your message will still be acknowledged while it's on the queue, rather than after it's been fully processed.

Yes you are correct and we understand this. But we are using  `@Incoming` only in status resource and there is no queue in that class. Plus I know what you are implying to use Manual acknowledgment but we have a separate guide to talk about it.

**Comment by Azquelt** [comment]
> Plus I know what you are implying to use Manual acknowledgment but we have a separate guide to talk about it.

I'm suggesting that you either write your application in such a way that acknowledgement is handled correctly, or acknowledge in the guide that you are not doing so and that users need to take additional steps beyond those described in the guide if they don't want to lose data.

It would be fair to treat this guide as an introduction, as long as you point out what isn't covered and point towards a later guide which goes into acknowledgement in more detail.

> How would you achieve this with Outgoing annotation? Don't u need some Kakfa API to check the offset value to make sure that the message in acknowledged?

No, the kafka connector will do this for you and acknowledge the message once it's been delivered to the kafka broker.

You can do something like this:

```
@POST
public CompletionStage<Order> placeOrder(Order order) {
    CompletionStage<Order> cs = new CompletionStage<>();
    Message<Order> orderMessage = Message.of(order, () -> {
        cs.complete(order);
        return CompletableFuture.completedFuture(null);
    });
    myQueue.put(orderMessage);
    return cs;
}

@Outgoing("my-channel")
public Message<Order> sendOutgoing() {
    return myQueue.take();
}
```

In `placeOrder()` we first create a `CompletionStage` to contain the eventual result we want to return to the user. Then we create a `Message` object and say "when this message is acknowledged, complete that `CompletionStage` with the order which was recieved". Finally we put the `Message` (not the `Order`) on the queue. We then return the `CompletionStage` to JAX-RS which will wait for it to complete before sending the response.

When this `Message` is later sent, the connector will call the `ack()` method which will run the code which completes the `CompletionStage` and causes JAX-RS to send the response.

As I said above, if you don't want to get too into acknowledgements in this guide, that's fine, but it's worth knowing that reactive messaging does have this capability built in, and it can be used to write robust applications without getting into native messaging system APIs.

**Comment by ankitagrawa** [comment]
The application has been changed to System-Inventory and these points don't hold. Closing this issue for now.
