### ISSUE TITLE
microservice interaction picture

### ISSUE THREAD

**Issue by Emily-Jiang** [OpenLiberty/draft-guide-microprofile-reactive-messaging#50]
There should be a diagraph to describe the relationship of the microservices. In particular, the microservices that need to talk to Kafka should be highlighted and having the configuration explained.

**Comment by ankitagrawa** [comment]
I think we are doing that.

There are two images in the guide and instructions in the guide on the config as well. Do you have anything specific on mind?

<img width="548" alt="image" src="https://user-images.githubusercontent.com/8294670/77454446-ede32b80-6dce-11ea-84ce-efeb872d0384.png">

<img width="546" alt="image" src="https://user-images.githubusercontent.com/8294670/77454492-fc314780-6dce-11ea-8502-f497b4cc4be0.png">

@Emily-Jiang

**Comment by Emily-Jiang** [comment]
ok, thanks
