### ISSUE TITLE
SME review

### ISSUE THREAD

**Issue by Azquelt** [OpenLiberty/draft-guide-microprofile-reactive-messaging#51]
### What you'll learn

> Apache Kafka is a stream-processing platform that manages communication in distributed systems. Communication is message-oriented, and follows the publish-subscribe model. Kafka allows for real-time stream processing and distributed, replicated storage of streams and messages. Kafka Producer is a client or a program, which produces the message and pushes it to the Topic. Whereas Kafka Consumer is a client or a program, which consumes the published messages from the Producer.

Apache Kafka is a stream-processing platform that manages communication in distributed systems. Communication is message-oriented, and follows the publish-subscribe model. Kafka allows for real-time stream processing and distributed, replicated storage of streams and messages. **A** Kafka **p**roducer is a client or a program, which produces messages and pushes **them to a topic**. **A** Kafka **c**onsumer is a client or a program, which consumes published messages **from a topic**.

> Imagine asynchronous programming as a restaurant.
This analogy is pretty good. :+1: 

> The OpenLiberty Cafe application is designed with reactive architecture.
I'm not entirely sure what this means. "Reactive" is a fairly vague term, so I'm not sure what "reactive architecture" is. You can either explain better what you mean here, or just drop this sentence and explain how the application works.

> backends for frontends
backend for frontend - we only have one of each

### Creating a Reactive Messaging application

In this section, "Outgoing" and "Incoming" should be `@Outgoing` and `@Incoming` when referring to the annotations.

> Channel is a bridge for transporting messages
Should be "A channel [...]"

> for transporting messages between service and messaging-broker
for transporting messages between different parts of the reactive system. This can be between the service and a messaging-broker, or between two components within the same service.

> Reactive messaging uses connectors to attach one end of a channel to other messaging technology
**MicroProfile Reactive Messaging** uses connectors to attach one end of a channel to **another** messaging technology

> Open Liberty includes the `liberty-kafka` connector for sending and receiving messages from an Apache Kafka.

Either "messages from Apache Kafka" or "messages from an Apache Kafka cluster"

The diagram you have here is great! :+1:

#### Configuring the MicroProfile Reactive Messaging

The title of this section should probably either be "Configuring MicroProfile Reactive Messaging", or "Configuring MicroProfile Reactive Messaging connectors"

> file, which configures the Kafka connector with the MicroProfile Reactive Messaging channels.

This needs to be worded better. You're telling MPRM to use connectors to connect certain channels to Apache Kafka and setting options on that connector.

Next paragraph is probably better off being broken up into bullet points.

Need to explain the format of the configuration keys
 - mp.messaging.connector.liberty-kafka.<property> applies to all channels using the liberty-kafka connector
 - mp.messaging.[incoming.<channelname>|outgoing.<channelname>].<property> applies to a particular channel
 - each channel which is to be connected using a connector must have the `connector` property defined to say which connector to use

Link to https://kafka.apache.org/documentation/#producerconfigs and https://kafka.apache.org/documentation/#consumerconfigs, not #api.

#### Building the Order microservice

We need to explain in this section how we're using rxJava to bridge between JAX-RS (non-reactive) and Reactive Messaging (reactive).

Something basic like "We use Flowable.create() from rxJava to create a Publisher and an associated emitter. Objects we send to the emitter will be sent though to the Publisher. We return the Publisher from our @Outgoing method and MPRM takes care of assigning the publisher to the channel.

> when the POST request of the endpoint /orders is called.

When an Order is sent in a POST request to the /orders endpoint.

> As soon as an order is added to the emitter, the Flowable.<Order>create() method retrieves and removes the orders.

This is not correct. We need to have explained the how we're using Flowable before so that this part makes sense.

"When an order is passed to the emitter, it is then sent, via the publisher, along the xxx channel to the configured connector, which receives the order and publishes it to the Kafka topic configured earlier."

#### Descriptions of other microservices

Some of these appear to be missing what the microservice _does_ with the order

> To get the service running, the Open Liberty server needs to be correctly configured.

To use MicroProfile Reactive Messaging, we must enable the feature in the server.xml file for each service.

#### Where to next

The links in this section are unhelpful:
 - microprofile.io has no information
 - microprofile API pages do not include MPRM yet
 - ordering of links should be MPRM specific first, followed by general MP

We should link to:
 - MPRM spec: https://download.eclipse.org/microprofile/microprofile-reactive-messaging-1.0/microprofile-reactive-messaging-spec.html
 - MPRM Javadoc: https://download.eclipse.org/microprofile/microprofile-reactive-messaging-1.0/apidocs/
 - any other general MP information

**Comment by ankitagrawa** [comment]
The application has been changed to System-Inventory and these points don't hold. Closing this issue for now.
