### ISSUE TITLE
Peer Review #2: Win

### ISSUE THREAD

**Issue by DannyS03** [OpenLiberty/draft-guide-microprofile-reactive-messaging#53]
Peer Review: review to be done by a peer member.

Functionality
---
- [x] Check that the guide has working instructions and sample code
- [x] Test the guide on 3 platforms: Mac, __Win__, Linux
- [x] If any URL visits, try them on different browsers: Firefox, Chrome, Safari
- [x] If any URL visits, try `curl` command where applicable

Formatting & Presentation
---
- [x] Check the quality of code according to the best coding practices
    - [x] Ensure that command substitutions use the `$(cmd)` format and not ``` `cmd` ```
    - [x] Ensure that the console output of the integrated tests do not include the `[INFO]` tab
- [x] Check the quality and presentation of guide according to [Structure and Style Guideline](https://github.com/OpenLiberty/draft-guides-template/wiki/Guidelines-for-Structure-and-Styles)
- [x] Check the consistency of guide with template and other guides
- [x] Examples with the right outcomes are provided
- [x] Example with the wrong outcomes, if any, are provided
- [x] Check that all licensing statements are properly stated in all files
- [x] Check that the `pom.xml`, `server.xml`, etc files are clean
- [x] Check that the directories are properly structured
- [x] Ensure that the guide is using the latest version of the `liberty-maven-plugin` or `liberty-gradle-plugin` where applicable
- [x] Check that some of these `page-tags` are used in a guide: `MicroProfile, Maven, Docker, Kubernetes, Gradle, Java EE, Security, Cloud`. Only these tags are visible on the website. Latest list [here](https://github.com/OpenLiberty/openliberty.io/blob/master/src/main/content/_includes/visible-tags.liquid).
- [x] Check the `attribution` statement is accurate for the guide
- [x] Verify the `travisTest.sh` script, if any, is accurate and consistent with other guides

Peer Testing: tests to be done by a peer member.

Guide’s contributor’s (if available, otherwise peer tester’s) responsibility:
- [x] Additional tests where applicable:
    - [x] Define test coverage and review with team (including guide contributor, if available)
    - [x] Define detail test cases
    - [x] Consider corner cases targeting the specific guide
    - [x] Consider different platform tests, ie, Mac, __Windows__, Linux
    - [x] Consider corner cases UI tests
    - [x] Consider testing URL on all browsers, ie, FF, Chrome, Safari
    - [x] Consider testing the `curl` command for URL visits
- [x] Consider building with both Maven and Gradle build tools
- [x] Testing with different IDEs, ie, Atom, Eclipse (Optional: VS.code, IntelliJ, Microclimate)
- [x] Run Acrolinx Checker on draft (above 70 score approximately)
- [x] Consider SEO title and description for the guides
- [x] Ensure automated test is enable, set up with Travis CI, and able to schedule tests
- [x] Run `diff -r start/ finish/` and there’s no differences
- [x] Ensure that the automation tests are able to run when PR is created

Peer Tester’s responsibility:
- [x] Check the appearance of the guide on test site for the following items:
    - [x] Table of contents
    - [x] Headings
    - [x] Paragraphs
    - [x] code snippets
    - [x] outputs
    - [x] links
    - [x] hotspots
- [x] Test the guide end-to-end with working instruction and sample code
- [x] Perform all the defined test cases

**Comment by DannyS03** [comment]
# Formatting & Presentation
## What you’ll learn
### What is MicroProfile Reactive Messaging?
- [ ] MicroProfile Reactive Messaging provides a way to build systems of microservices __which advocates__ responsiveness, location transparency, elasticity, resiliency to failure and temporal decoupling.

### What is Kafka?
- [ ] There should be mention of what a streaming platform is.
- [ ] Since this attempts to act as an _introduction_ to Kafka and it is being introduced, it seems better to mention that Kafka has four core API’s and that Kafka Producer and Kafka Consumer are API’s in Kafka… and then the section can be finished off by “Visit `Apache Kafka` for more information.

### What is asynchronous programming?
- [ ] For clarity, should have a generic introductory sentence about what asynchronous programming is, and then lead into the restaurant analogy.
- [ ] For clarity, should mention which microservices represent the Producer and Consumer.
<img width="556" alt="image" src="https://user-images.githubusercontent.com/25497083/77488383-72539f80-6e0b-11ea-9ddb-681734889869.png">

## Additional prerequisites
- [ ] Take out the `now`
```
You will now build and run the microservices in Docker containers. You can learn more about containerizing microservices with Docker in the Containerizing microservices guide.
```

## Building the Order microservice
- [ ] `pom.xml` doesn’t’ have to be a file hotspot as it is already being referenced in the section
<img width="565" alt="image" src="https://user-images.githubusercontent.com/25497083/77488046-76cb8880-6e0a-11ea-9c9e-0f287fb201d6.png">


## Configuring the server
- [ ] `server.xml` doesn’t have to be a file hotspot as it is already being referenced in the section.
<img width="558" alt="image" src="https://user-images.githubusercontent.com/25497083/77488061-82b74a80-6e0a-11ea-804b-8d14152a2910.png">

## Building the application
- [ ] Perhaps some elaboration on the `mvn -pl models install` command.
  - [ ] the `-pl` flag and the need to build the specific `models` project rather than all the projects.
<img width="547" alt="image" src="https://user-images.githubusercontent.com/25497083/77488084-96fb4780-6e0a-11ea-8f22-34851d15e04c.png">

## Trying the application
- [ ] The service __may__ take some time to become available.
<img width="528" alt="image" src="https://user-images.githubusercontent.com/25497083/77488120-b09c8f00-6e0a-11ea-9b4c-1b458554cd82.png">

### Place Orders
- [ ] Make a POST request to the /api/orders endpoint. To make this request, expand the POST endpoint on the UI __and__ click the Try it out button.

### Check IN_PROGRESS Order Status
- [ ] Remove `Just` and `if` and add a comma after `status`

```
Just in case if you see a NEW status then wait for a couple of seconds and click the Execute button again.
```

### Check READY Order Status
- [ ] Remove `Just` and `if` and add a comma after `status`
```
Just in case if you see an IN_PROGRESS status then wait for a couple of seconds and click the Execute button again.
```

### Complete an Order
- [ ] Expand the POST endpoint on the UI __and__ click the Try it out button.
- [ ] Remove the comma

```
Copy the following orderId into the text box, and then click the Execute button.
```
------------
#### very minor indentation difference in `pom.xml` files for the following:
  - [ ] `finish/bar/pom.xml` has extra indentation in following dependancy:
  - [ ] `finish/servingWindow/pom.xml/` has extra indentation in the following dependany:
    ```
     <dependency>
           <groupId>io.reactivex.rxjava3</groupId>
           <artifactId>rxjava</artifactId>
            <version>3.0.0</version>
     </dependency>
    ```
# Functionality
- [ ] Looks like ConfigProperty for `beverageOrderConsume` in the start directory accidentally uses the hotspot name `bevOrderConsume` (from BarService.java), in `BarReadinessCheck.java`

## Building the application
- [ ] Perhaps unnecessary to have.
<img width="559" alt="image" src="https://user-images.githubusercontent.com/25497083/77488156-cdd15d80-6e0a-11ea-8193-5893ebac57ae.png">

- Wouldn’t the docker image download/update the image if needed when containerizing the microservices?

- _This is the only time Apache`ZooKeeper` is mentioned._

------------
#### Note:
```
Only in start/order: target
Only in start/servingWindow: .classpath
Only in start/servingWindow: .project
Only in start/servingWindow: .settings
Only in start/servingWindow: target
Only in start/status: .classpath
Only in start/status: .project
Only in start/status: .settings
```

**Comment by ankitagrawa** [comment]
> Only in start/order: target

I don't see it.
https://github.com/OpenLiberty/draft-guide-microprofile-reactive-messaging/tree/dev/start/order

> Only in start/servingWindow: .classpath
> Only in start/servingWindow: .project
> Only in start/servingWindow: .settings

> Only in start/servingWindow: target
> Only in start/status: .classpath
> Only in start/status: .project
> Only in start/status: .settings

I guess it's IDE issue. I don't see it in git.

**Comment by DannyS03** [comment]
discussed and addressed.
