### ISSUE TITLE
Peer Review - Mac

### ISSUE THREAD

**Issue by MaiHameed** [OpenLiberty/draft-guide-microprofile-reactive-messaging#54]
Peer Review: review to be done by a peer member. 

Functionality
---
- [ ] Check that the guide has working instructions and sample code
- [ ] Test the guide on 3 platforms: 
    - [x] Mac 
    - [ ] Windows 
    - [ ] Linux 
- [ ] If any URL visits, try them on different browsers: 
    - [ ] Firefox 
    - [x] Chrome 
    - [x] Safari 
- [ ] If any URL visits, try `curl` command where applicable 

Formatting & Presentation
---
- [x] Check the quality of code according to the best coding practices
    - [x] Ensure that command substitutions use the `$(cmd)` format and not ``` `cmd` ```
    - [x] Ensure that the console output of the integrated tests do not include the `[INFO]` tab
- [x] Check the quality and presentation of guide according to [Structure and Style Guideline](https://github.com/OpenLiberty/draft-guides-template/wiki/Guidelines-for-Structure-and-Styles)
- [x] Check the consistency of guide with template and other guides
- [x] Examples with the right outcomes are provided
- [x] Example with the wrong outcomes, if any, are provided
- [x] Check that all licensing statements are properly stated in all files
- [x] Check that the `pom.xml`, `server.xml`, etc files are clean
- [x] Check that the directories are properly structured
- [x] Ensure that the guide is using the latest version of the `liberty-maven-plugin` or `liberty-gradle-plugin` where applicable
- [x] Check that some of these `page-tags` are used in a guide: `MicroProfile, Maven, Docker, Kubernetes, Gradle, Java EE, Security, Cloud`. Only these tags are visible on the website. Latest list [here](https://github.com/OpenLiberty/openliberty.io/blob/master/src/main/content/_includes/visible-tags.liquid). 
- [x] Check the `attribution` statement is accurate for the guide
- [x] Verify the `travisTest.sh` script, if any, is accurate and consistent with other guides

Peer Testing: tests to be done by a peer member.

Guide’s contributor’s (if available, otherwise peer tester’s) responsibility: 
- [ ] Additional tests where applicable: 
    - [ ] Define test coverage and review with team (including guide contributor, if available)
    - [ ] Define detail test cases 
    - [ ] Consider corner cases targeting the specific guide
    - [ ] Consider different platform tests, ie, Mac, Windows, Linux
    - [ ] Consider corner cases UI tests
    - [ ] Consider testing URL on all browsers, ie, FF, Chrome, Safari
    - [ ] Consider testing the `curl` command for URL visits
- [ ] Consider building with both Maven and Gradle build tools 
- [x] Testing with different IDEs, ie, Atom, Eclipse (Optional: VS.code, IntelliJ, Microclimate)
- [ ] Run Acrolinx Checker on draft (above 70 score approximately)
- [ ] Consider SEO title and description for the guides 
- [ ] Ensure automated test is enable, set up with Travis CI, and able to schedule tests 
- [x] Run `diff -r start/ finish/` and there's no differences
- [x] Ensure that the automation tests are able to run when PR is created

Peer Tester’s responsibility: 
- [x] Check the appearance of the guide on test site for the following items: 
    - [x] Table of contents 
    - [x] Headings
    - [x] Paragraphs
    - [x] code snippets
    - [x] outputs
    - [x] links
    - [x] hotspots 
- [ ] Test the guide end-to-end with working instruction and sample code
- [ ] Perform all the defined test cases 

## Check IN_PROGRESS Order Status
- In this section, maybe highlight the asynchronous portion of the guide by stating that either burger or coke can be order `0001`, it's a good learning point.

---

- The Bar service is throwing errors:
```
[ERROR   ] CWMCG5003E: The [BackedAnnotatedField] @Inject @ConfigProperty io.openliberty.guides.bar.health.BarReadinessCheck.groupId InjectionPoint dependency was not resolved. Error: java.util.NoSuchElementException: CWMCG0015E: The property mp.messaging.incoming.bevOrderConsume.group.id was not found in the configuration.
	at com.ibm.ws.microprofile.config.impl.AbstractConfig.getValue(AbstractConfig.java:176)
	at [internal classes]

[ERROR   ] CWWKZ0002E: An exception occurred while starting the application bar. The exception message was: com.ibm.ws.container.service.state.StateChangeException: org.jboss.weld.exceptions.DeploymentException: WELD-001408: Unsatisfied dependencies for type String with qualifiers @ConfigProperty
  at injection point [BackedAnnotatedField] @Inject @ConfigProperty io.openliberty.guides.bar.health.BarReadinessCheck.kafkaServer
  at io.openliberty.guides.bar.health.BarReadinessCheck.kafkaServer(BarReadinessCheck.java:0)
```

**Comment by ankitagrawa** [comment]
The application has been changed to System-Inventory and these points don't hold. Closing this issue for now.
