### ISSUE TITLE
Peer Review: Linux

### ISSUE THREAD

**Issue by k-rtik** [OpenLiberty/draft-guide-microprofile-reactive-messaging#55]
### Configuring MicroProfile Reactive Messaging connectors
- [x] From
  > In order to configure the MicroProfile Reactive Messaging connectors, We need to format the configuration keys as follows

  to 

  > In order to configure the MicroProfile Reactive Messaging connectors, we need to format the configuration keys as follows

- [x] Should
  > The `key.serializer` and `value.serializer` properties characterize how to serialize the messages. Similarly `value.deserializer` properties define how to deserialize the messages.

  be 

  > The `key.serializer` and `value.serializer` properties characterize how to serialize the messages. Similarly the `key.deserializer` and `value.deserializer` properties define how to deserialize the messages.

  ?

### Building the Order microservice
- [x] The hotspot for `microprofile-config.properties` might not be necessary since the next couple keywords are hotspots in the same file. Should **Publisher** be a keyword?
  > Objects we send to the emitter will be sent to the Publisher. We return the Publisher from our `@Outgoing("food")` or `@Outgoing("beverage")` channels, which are configured in the `microprofile-config.properties` `food` or `beverage` streams and MicroProfile Reactive Messaging takes care of assigning the publisher to the channel.

- [x] The hotspot for `pom.xml` might not be necessary since it's referenced in the Update arrow
  > In order to develop the MicroProfile Reactive Messaging application using Maven, add the `microprofile-reactive-messaging-api`, `kafka-clients`, and `rxjava` dependencies to the `pom.xml`

### Configuring the server
- [x] The hotspot for `server.xml` might not be necessary since it's referenced in the Update arrow and other hotspot keyword
  > Configure the server to enable MicroProfile Reactive Messaging by adding mpReactiveMessaging-1.0 feature element to the server.xml.
The rest of the microservices have server.xml already configured. 

### Check IN_PROGRESS Order Status

- [x] Suggest changing 
  > Just in case if you see a NEW status then wait for a couple of seconds and click the Execute button again.

  to
  > If you see a NEW status, wait for a couple of seconds and click the Execute button again.

### Check READY Order Status

- [x] Suggest changing
  > Just in case if you see an IN_PROGRESS status then wait for a couple of seconds and click the Execute button again.

  to
  > If you see an IN_PROGRESS status, wait for a couple of seconds and click the Execute button again.

**Comment by ankitagrawa** [comment]
> Building the Order microservice
> 
> The hotspot for microprofile-config.properties might not be necessary since the next couple keywords are hotspots in the same file. Should Publisher be a keyword?
> 
>     Objects we send to the emitter will be sent to the Publisher. We return the Publisher from our @Outgoing("food") or @Outgoing("beverage") channels, which are configured in the microprofile-config.properties food or beverage streams and MicroProfile Reactive Messaging takes care of assigning the publisher to the channel.
> 
> The hotspot for pom.xml might not be necessary since it's referenced in the Update arrow
> 
>     In order to develop the MicroProfile Reactive Messaging application using Maven, add the microprofile-reactive-messaging-api, kafka-clients, and rxjava dependencies to the pom.xml
> 

In my previous feedback I was told to add them as a hotspot.

**Comment by k-rtik** [comment]
LGTM
