### ISSUE TITLE
Peer Review - Mac

### ISSUE THREAD

**Issue by MaiHameed** [OpenLiberty/draft-guide-microprofile-reactive-messaging#65]
Peer Review: review to be done by a peer member. 

Functionality
---
- [x] Check that the guide has working instructions and sample code
- [ ] Test the guide on 3 platforms: 
    - [x] Mac 
    - [ ] Windows 
    - [ ] Linux 
- [x] If any URL visits, try them on different browsers: 
    - [x] Firefox 
    - [x] Chrome 
    - [x] Safari 
- [x] If any URL visits, try `curl` command where applicable 

Formatting & Presentation
---
- [x] Check the quality of code according to the best coding practices
    - [x] Ensure that command substitutions use the `$(cmd)` format and not ``` `cmd` ```
    - [x] Ensure that the console output of the integrated tests do not include the `[INFO]` tab
- [x] Check the quality and presentation of guide according to [Structure and Style Guideline](https://github.com/OpenLiberty/draft-guides-template/wiki/Guidelines-for-Structure-and-Styles)
- [x] Check the consistency of guide with template and other guides
- [x] Examples with the right outcomes are provided
- [x] Example with the wrong outcomes, if any, are provided
- [x] Check that all licensing statements are properly stated in all files
- [x] Check that the `pom.xml`, `server.xml`, etc files are clean
- [x] Check that the directories are properly structured
- [x] Ensure that the guide is using the latest version of the `liberty-maven-plugin` or `liberty-gradle-plugin` where applicable
- [x] Check that some of these `page-tags` are used in a guide: `MicroProfile, Maven, Docker, Kubernetes, Gradle, Java EE, Security, Cloud`. Only these tags are visible on the website. Latest list [here](https://github.com/OpenLiberty/openliberty.io/blob/master/src/main/content/_includes/visible-tags.liquid). 
- [x] Check the `attribution` statement is accurate for the guide
- [ ] Verify the `travisTest.sh` script, if any, is accurate and consistent with other guides

Peer Testing: tests to be done by a peer member.

Guide’s contributor’s (if available, otherwise peer tester’s) responsibility: 
- [ ] Additional tests where applicable: 
    - [ ] Define test coverage and review with team (including guide contributor, if available)
    - [ ] Define detail test cases 
    - [ ] Consider corner cases targeting the specific guide
    - [ ] Consider different platform tests, ie, Mac, Windows, Linux
    - [ ] Consider corner cases UI tests
    - [ ] Consider testing URL on all browsers, ie, FF, Chrome, Safari
    - [ ] Consider testing the `curl` command for URL visits
- [ ] Consider building with both Maven and Gradle build tools 
- [ ] Testing with different IDEs, ie, Atom, Eclipse (Optional: VS.code, IntelliJ, Microclimate)
- [ ] Run Acrolinx Checker on draft (above 70 score approximately)
- [x] Consider SEO title and description for the guides 
- [ ] Ensure automated test is enable, set up with Travis CI, and able to schedule tests 
- [x] Run `diff -r start/ finish/` and there's no differences
- [ ] Ensure that the automation tests are able to run when PR is created

Peer Tester’s responsibility: 
- [x] Check the appearance of the guide on test site for the following items: 
    - [x] Table of contents 
    - [x] Headings
    - [x] Paragraphs
    - [x] code snippets
    - [x] outputs
    - [x] links
    - [x] hotspots 
- [x] Test the guide end-to-end with working instruction and sample code
- [ ] Perform all the defined test cases 

---

## Additional prerequisites
- [x]  `Kafka docker containers`, capitalize ~docker~ -> Docker

## What is MicroProfile Reactive Messaging?
- [x] Add a comma between `failure` and `and` in `resiliency to failure and temporal decoupling`.
- [x] add `the` between `See` and `MicroProfile` in `See MicroProfile Reactive Messaging Specification`.

## What is Kafka?
- [x] Remove the comma after `System` in `microservices, System, and Inventory.`
- [x] Remove the comma after `System` in `You’ll update the System, and Inventory microservices`

## Building Producer in the System microservice
- [x] Add a `the` between `Building` and `[Producer|Consumer]` in the titles: `Building [Producer|Consumer] in the [System|Inventory] microservice`
- [x] Remove the `a` in ` method creates a CPU system load statistics`.
- [x] Add a space between the `#` and `liberty`, and capitalize `Kafka` and `Liberty` in the `#liberty kafka connector`  comment in the `[system|inventory]/microprofile-config.properties` file
- [x] Remove the hotspot comment tags from the `start/[system|inventory]/pom.xml` and the `start/.../InventoryResource.java` files, they only need to be in the `finish/` directory.

## Building Consumer in the Inventory microservice
- [x] `microservices` should be `microservice` in `from the System microservices`
- [x] The sentence `It’s also a RESTful service that is served at the inventory/systems endpoint.` Should be `It’s also a RESTful service that is served at the inventory endpoint.` and highlight the `@Path("/inventory")` annotation since that's technically where the application is served, the `inventory/systems` is just one of the additional endpoints of the overall inventory application.

## Configuring the MicroProfile Reactive Messaging connectors
- [x] `mp.messaging.[incoming.|outgoing.].` should be `mp.messaging.[incoming|outgoing].`
- [x] Change `Both the microservices System, and Inventory contain microprofile-config.properties file.` to `Both the System and Inventory microservices contain the microprofile-config.properties file.`
- [x] `MicroProfile Reactive Messaging uses connectors to connect certain channels to Apache Kafka and setting options on those connectors.` The `setting options` bit is confusing. I don't understand what you mean by that.
- [ ]  `The key.serializer and value.serializer properties characterize how to serialize the messages.` Add a note and possible a hotspot to the custom value serializer in the `SystemLoad` class.
- [x] The `systemLoadTopic` hotspot links to the `system/microprofile-config.properties` file instead of the `inventory/microprofile-config.properties` file.

## Configuring the server
- [x] The `The Inventory microservice has server.xml already configured.`, `server.xml` hotspot should link to the `inventory/.../server.xml` instead of the `system` since there are slight differences.
- [x] The `[start|finish]/inventory/.../server.xml` says `<server description="Order Service">`, needs to be changed to `Inventory Service`.

## Building the application
- [x] Remove the comma after `System` in `run the System, and Inventory microservices`
- [x] Capitalize `Docker` in `open-liberty docker image`
- [x] Reword `Run the following command to download or update the open-liberty docker image to latest.` to `Run the following command to download or update to the latest open-liberty docker image.`

## Testing the application
- [x] The output of the inventory URL visit is mismatched. Mine looks like:
```
[
    {
        "hostname": "38cfc2b63a96",
        "systemLoad": 2.41
    }
]
```
- [x] It mentioned that the inventory lists ALL systems, however there is always only 1 system in the inventory since we only have 1 system service running. The sentence is misleading to mention ALL systems if we only tell the user to deploy 1. Maybe rewrite to mention that we can scale the application up, however there will only be 1 until then.
- [x] The `travisTest.sh` script is outdated for the new guide.

**Comment by ankitagrawa** [comment]
> It mentioned that the inventory lists ALL systems, however there is always only 1 system in the inventory since we only have 1 system service running. The sentence is misleading to mention ALL systems if we only tell the user to deploy 1. Maybe rewrite to mention that we can scale the application up, however there will only be 1 until then.

Spoke to Gilbert about it. Seems like we are good with this.

**Comment by ankitagrawa** [comment]
Addressed the feedback. Closing the issue.
