### ISSUE TITLE
Peer Review - Linux

### ISSUE THREAD

**Issue by NimG98** [OpenLiberty/draft-guide-microprofile-reactive-messaging#66]
Peer Review: review to be done by a peer member. 

Functionality
---
- [x] Check that the guide has working instructions and sample code
- [x] Test the guide on 3 platforms: Mac, Win, Linux
- [x] If any URL visits, try them on different browsers: Firefox, Chrome, Safari
- [ ] If any URL visits, try `curl` command where applicable 

Formatting & Presentation
---
- [x] Check the quality of code according to the best coding practices
    - [ ] Ensure that command substitutions use the `$(cmd)` format and not ``` `cmd` ```
    - [x] Ensure that the console output of the integrated tests do not include the `[INFO]` tab
- [x] Check the quality and presentation of guide according to [Structure and Style Guideline](https://github.com/OpenLiberty/draft-guides-template/wiki/Guidelines-for-Structure-and-Styles)
- [x] Check the consistency of guide with template and other guides
- [x] Examples with the right outcomes are provided
- [x] Example with the wrong outcomes, if any, are provided
- [ ] Check that all licensing statements are properly stated in all files
- [x] Check that the `pom.xml`, `server.xml`, etc files are clean
- [x] Check that the directories are properly structured
- [x] Ensure that the guide is using the latest version of the `liberty-maven-plugin` or `liberty-gradle-plugin` where applicable
- [x] Check that some of these `page-tags` are used in a guide: `MicroProfile, Maven, Docker, Kubernetes, Gradle, Java EE, Security, Cloud`. Only these tags are visible on the website. Latest list [here](https://github.com/OpenLiberty/openliberty.io/blob/master/src/main/content/_includes/visible-tags.liquid). 
- [x] Check the `attribution` statement is accurate for the guide
- [x] Verify the `travisTest.sh` script, if any, is accurate and consistent with other guides

Peer Testing: tests to be done by a peer member.

Guide’s contributor’s (if available, otherwise peer tester’s) responsibility: 
- [x] Additional tests where applicable: 
    - [x] Define test coverage and review with team (including guide contributor, if available)
    - [x] Define detail test cases 
    - [x] Consider corner cases targeting the specific guide
    - [x] Consider different platform tests, ie, Mac, Windows, Linux
    - [x] Consider corner cases UI tests
    - [x] Consider testing URL on all browsers, ie, FF, Chrome, Safari
    - [ ] Consider testing the `curl` command for URL visits
- [x] Consider building with both Maven and Gradle build tools 
- [x] Testing with different IDEs, ie, Atom, Eclipse (Optional: VS.code, IntelliJ, Microclimate)
- [ ] Run Acrolinx Checker on draft (above 70 score approximately)
- [x] Consider SEO title and description for the guides 
- [x] Ensure automated test is enable, set up with Travis CI, and able to schedule tests 
- [x] Run `diff -r start/ finish/` and there's no differences
- [x] Ensure that the automation tests are able to run when PR is created

Peer Tester’s responsibility: 
- [x] Check the appearance of the guide on test site for the following items: 
    - [x] Table of contents 
    - [x] Headings
    - [x] Paragraphs
    - [x] code snippets
    - [x] outputs
    - [x] links
    - [x] hotspots 
- [x] Test the guide end-to-end with working instruction and sample code
- [x] Perform all the defined test cases

**Comment by NimG98** [comment]
## Additional Prerequisites 
- [ ] capitalize Docker
    > The application also requires Apache Kafka however you will be using Kafka docker containers to reduce the installation and configuration.

## What you'll learn
- [ ] other guides use `system` and `inventory` microservice as lowercase
- [ ] remove comma after `System`
    > The application that you will be working with consists of two microservices, `System`, and `Inventory`. 
- [ ] remove comma after `System`
    > You’ll update the `System`, and `Inventory` microservices to use MicroProfile Reactive Messaging for message passing. 
- [ ] The titles "Restful API" and "MP Reactive Messaging" in the image could be better positioned to the centre of their respective curly bracket
    ![image](https://user-images.githubusercontent.com/46586499/78720236-52d07280-78f3-11ea-8e81-c691f4249350.png)
- [ ] in the pic, the endpoint `/systems/{hostid}` should be `/systems/{hostId}` i think
    ![image](https://user-images.githubusercontent.com/46586499/78720923-9a0b3300-78f4-11ea-826c-5d25d2b6ad72.png)

## MicroProfile Reactive Messaging Key Concepts
- [ ] add periods for the last sentence in the `@ Outgoing` and `@Incoming` sections.
- [ ] Maybe say "Here's a detailed diagram..."
    > Detailed diagram with the MicroProfile Reactive Messaging channels, Apache Kafka topics and the interaction between them :

## Building Producer in the System microservice
- [ ] should there be a word before Producer in the section title, like "a" or "the"
- [ ] when the users are asked to `Replace the Maven configuration file.`, the `system/pom.xml` in start already has the dependencies it says to add. The only difference between the `finish/system/pom.xml` and `start/system/pom.xml` right now is the hotspot tags
- [ ] `Publisher` is used with back-ticks once and not the other times:
    ![image](https://user-images.githubusercontent.com/46586499/78721895-616c5900-78f6-11ea-872c-cfb76cac72de.png)

## Building Consumer in the Inventory microservice
- [ ] should there be a word before Consumer in the section title, like "a" or "the"
- [ ] change `inventory/systems endpoint.` to `/inventory/systems endpoint.`

## Configuring the MicroProfile Reactive Messaging connectors
- [ ] remove the `-` before the `:` here:
    ![image](https://user-images.githubusercontent.com/46586499/78792997-d9329600-797f-11ea-904c-e67f78794138.png)
- [ ] add "a" after contain:
    > Both the microservices `System`, and `Inventory` contain `microprofile-config.properties` file.
- [ ] Change:
    > The `Inventory` microservices use similar `microprofile-config.properties` configuration to define it’s required incoming stream.

    To:
    > The `inventory` microservice use**s a** similar `microprofile-config.properties` configuration to define **its** required incoming stream.

### Testing the application
- [ ] output should not be in green box, but in a gray box
    ![image](https://user-images.githubusercontent.com/46586499/78795608-2f550880-7983-11ea-9fe2-422d2579234e.png)
- [ ] output on Linux for me is a list then the json properties
    ![image](https://user-images.githubusercontent.com/46586499/78795673-41cf4200-7983-11ea-8a83-aded9a871c81.png)
- [ ] the {hostId} url shouldn't be clickable
    ![image](https://user-images.githubusercontent.com/46586499/78795771-63c8c480-7983-11ea-9315-3f0dcc3969f3.png)

**Comment by ankitagrawa** [comment]
done except travisTest.sh

**Comment by ankitagrawa** [comment]
Addressed the feedback. Closing the issue.
