### ISSUE TITLE
Review feedback

### ISSUE THREAD

**Issue by Azquelt** [OpenLiberty/draft-guide-microprofile-reactive-messaging#68]
> Temporal decoupling of services in a microservice-based architecture can be achieved using asynchronous communication. MicroProfile Reactive Messaging provides a way to build systems of microservices which advocates responsiveness, location transparency, elasticity, resiliency to failure, and temporal decoupling. This helps in enforcing asynchronous message passing between the different parts of the system. See the MicroProfile Reactive Messaging Specification for more information.

Still not really sure about this paragraph. Reactive Messaging falls a bit short of those goals in its current state, plus we don't really talk about how those things are achieved in this guide.

> - `mp.messaging.[incoming|outgoing].` : Applies to a particular channel

This should probably have a placeholder for the channel name.

I.e. `mp.messaging.[incoming|outgoing].<channel name>.`

Maybe even include a placeholder for the property as well: `mp.messaging.[incoming|outgoing].<channel name>.<property name>`

> Each channel which is to be connected using a connector must have the connector property defined to say which connector to use

Use code quotes around the word connector in "`connector` property"

> Both the `system` and `inventory` microservices contain the `microprofile-config.properties` file. MicroProfile Reactive Messaging uses connectors to connect certain channels to Apache Kafka and setting properties on those connectors.

This paragraph doesn't make a lot of sense. How about this instead:

"Both the `system` and `inventory` microservices use connectors to connect certain channels to Apache Kafka and these connectors are configured by setting properties using MicroProfile Config. This is done by setting the required properties inside the `microprofile-config.properties` file included in each application."

> The `mp.messaging.connector.liberty-kafka.bootstrap.servers` property defines the Kafka connector for the Open Liberty runtime.

This doesn't make much sense either. How about this:

The `mp.messaging.connector.liberty-kafka.bootstrap.servers` property configures the hostname and port of the Kafka server for all channels which use the Kafka connector.

> The `system` microservice uses an outgoing stream `systemLoad` to send messages to the `systemLoadTopic` topic in the Kafka messaging-broker, so that the `inventory` microservices can consume the messages.

The `system` microservice uses an outgoing connector to send messages from the `systemLoad` channel to the `systemLoadTopic` topic in the Kafka messaging-broker, so that the `inventory` microservices can consume the messages.

> The `JsonbSerializer()` method in the `SystemLoad` class defines the custom value for the `value.serializer`.

`JsonbSerializer` isn't a method, it's a (static inner) class.

I don't think it's correct to say it "defines the custom value" either. Maybe we could put something like:

"The class `JsonbSerializer` implements the logic for turning a `SystemLoad` object into json and is configured as the `value.serializer`"

> The `inventory` microservice listens to messages from an incoming stream`systemLoad`, wherein the messages are sent by the `system` microservice through the `systemLoadTopic` topic in the Kafka messaging-broker.

The `inventory` microservice uses an incoming connector to receive messages on the `systemLoad` channel which were sent by the `system` microservice to the `systemLoadTopic` in the Kafka messaging-broker.

> The SystemLoadDeserializer() method in the SystemLoad class defines the custom value for the value.deserializer.

Change this in the same way as the sentence about `JsonbSerializer` above.

> The `@GET` http://localhost:9085/inventory/system/{hostId} microservice endpoint gives you the CPU usage properties for a particular host.

The URL needs code tags. This could also be reworded to be similar to the previous paragraph. Something like: "You can use the `http://localhost:9085/inventory/system/{hostId}` URL to see the CPU usage properties for one particular system."

**Comment by Azquelt** [comment]
Also, it might be nicer if `JsonbSerializer` was named `SystemLoadSerializer` to match `SystemLoadDeserializer` (or vice versa). Makes it more obvious that they to the opposite of each other.

**Comment by ankitagrawa** [comment]
Addressed the feedback.

**Comment by Azquelt** [comment]
> `mp.messaging.connector.liberty-kafka.` : Applies to all channels using the liberty-kafka connector

Add `<property name>` to match the following line.

**Comment by Azquelt** [comment]
The class `SystemLoadDeserializer()` implements the logic for turning a `SystemLoad` object into json and is configured as the `value.deserializer`.

No, it does the reverse, turning json into a `SystemLoad` object.

> The class `SystemLoadSerializer()`
> The class `SystemLoadDeserializer()`

Remove parentheses because we're talking about a class, not a method.

**Comment by ankitagrawa** [comment]
addressed. @Azquelt

**Comment by Azquelt** [comment]
Looks good, thanks :+1:
