### ISSUE TITLE
Review feedback

### ISSUE THREAD

**Issue by GraceJansen** [OpenLiberty/draft-guide-microprofile-reactive-messaging#70]
"Imagine asynchronous programming as a restaurant. After you’re seated, a waitstaff takes your order. Then, you must wait a few minutes for your food to be prepared. While your food is being prepared, your waitstaff may take more orders or serve other tables. After your food is ready, your waitstaff brings out the food to your table. However, in a synchronous model, the waitstaff must wait for your food to be prepared before serving any other customers. This method blocks other customers from placing orders or receiving their food."
--> did we want to keep in references to the restaurant app?

"system load average data"
--> average system load is used later on, this sounds better

**Comment by ankitagrawa** [comment]
> "Imagine asynchronous programming as a restaurant. After you’re seated, a waitstaff takes your order. Then, you must wait a few minutes for your food to be prepared. While your food is being prepared, your waitstaff may take more orders or serve other tables. After your food is ready, your waitstaff brings out the food to your table. However, in a synchronous model, the waitstaff must wait for your food to be prepared before serving any other customers. This method blocks other customers from placing orders or receiving their food."
> --> did we want to keep in references to the restaurant app?

rest client async guide has a similar reference. Since reactive messaging guides are the next set of guides after rest client async, I feel we should keep it. Moreover it explains the asynchronous programming concept precisely.  

> "system load average data"
> --> average system load is used later on, this sounds better

done @GraceJansen

**Comment by GraceJansen** [comment]
ok yep, just had a look at the rest async guide and see that that also has this reference. Thanks for clarifying that. Feel that it's good to have synchronicity across guides. Looks good to me. Appreciate the slimmed down app too.
