### ISSUE TITLE
Review feedback on overall guide structure, style, and format

### ISSUE THREAD

**Issue by lauracowen** [OpenLiberty/draft-guide-microprofile-reactive-messaging#73]
Overall, I think you've done a good job of writing this and the flow of the guide works well. In the context of the guide format, it needs to be shorter, more concise, and more focused, so that only the important concepts are explained and emphasised. My feedback below is a mixture of comments/questions, and edits to the text for you to apply (mostly rejigging the order of sentences within a section, sometimes adding in extra sentences or removing others, and sometimes tweaking existing sentences to clarify the language):

- Guide intro
  - [x] we shouldn't have the MP feature name in the heading/title of the guide. It just needs to be optimised for SEO and meaningfulness. eg "Creating reactive Java microservices" or "Creating asynchronous Java microservices" or something like that.
  - [x] Similarly, the abstract (first sentence) should focus on what they get out of it before getting to what technology they use. So rather than "Learn how to use MicroProfile Reactive Messaging to implement an application with a reactive architecture.", something like "Learn how to write asynchronous Java microservices using MicroProfile Reactive Messaging." or "Learn how to write reactive Java microservices using MicroProfile Reactive Messaging."
- What you'll learn section
  - [x] This section is too long and doesn't need to focus on so many different concepts. I've drafted a new version here, though it could do with making even shorter ideally. I've reordered what you've written to emphasise the concepts slightly differently and flow the explanations more:
  >
  > You will learn how to build reactive microservices that can send requests to other microservices, and asynchronously receive and process the responses. You will use an external messaging system to handle the asynchronous messages that are sent and received between the microservices as streams of events. MicroProfile Reactive Messaging makes it easy to write and configure your application to send, receive, and process the events efficiently.
  >
  >Reactive microservices are responsive and resilient under varying workloads because they receive, process, and send messages asynchronously without blocking other work. For example, in a restaurant, a waitress might come to your table and take your order. Then, while you are waiting for your food to be prepared, she serves other tables, taking their orders too. When your food is ready, she brings your food to your table, then continues to serve the other tables too. The waitress is operating asynchronously; if she were to operate synchronously, she would have to take your order and then wait until she had brought your food to your table before she could serve any other tables. This is clearly not an efficient way to operate a restaurant. Similarly, sending and receiving messages synchronously between microservices is not an efficient way to run microservices.
  >
  >HTTP request calls from a REST client to another microservice can be time-consuming; the network might be slow, or the other service might be overwhelmed with requests and can't respond quickly. In a reactive system, a microservice sends an HTTP request to another microservice then continues to send other calls, and to receive and process other responses. When the microservice receives a response to the original request, it can process that request but, in the meantime, it is not blocked from completing other work.
  >
  >MicroProfile Reactive Messaging provides an easy way to asynchronously send, receive, and process messages that are received as continuous streams of events. You simply annotate application beans' methods and Open Liberty converts the annotated methods to reactive streams-compatible publishers, subscribers, and processors and connects them up to each other. MicroProfile Reactive Messaging provides a Connector API so that your methods can be connected to the external messaging systems that produce and consume the streams of events, such as Apache Kafka <link to a good Apache Kafka introduction>.
  >
  >The application in this guide consists of two microservices, `system` and `inventory`. Every 15 seconds, the `system` microservice calculates and publishes an event containing its current average system load. The `inventory` microservice subscribes to that information so that it can keep an updated list of all the systems and their current system loads. The current inventory of systems can be accessed the REST endpoint `@GET REST...etc`. You'll create the `system` and `inventory` microservices using MicroProfile Reactive Messaging.
  >
  >**diagram here - could it have some of the white space top and bottom removed so it doesn't take up so much vertical space?**
  - [ ] Can you use "waiter" or "waitress" instead of "a waitstaff" which isn't a term used outside North America and reads oddly to me (esp as "staff" is usually means multiple people not one person).
- Additional prerequisites section
  - [x] This section can be shortened, like this:
  > Install Docker (see the official Docker documentation) and start your Docker environment. You will build and run the microservices in Docker containers. An installation of Apache Kafka is provided in another Docker container.
  - [x] Why do we need Zookeeper for this app? It seems like unnecessary complexity for such a simple app - what does it provide here?
- Try what you'll build section
  - [x] We don't currently have one. I know that's because it's a lot of commands to start the app. However, at this stage they don't need to care about how you do it so is it worth/possible to have a single script that runs all the commands listed in the "Building the application" section so that the reader can run the app to see what happens before they start the guide (like they can in other guides)?
- MicroProfile Reactive Messaging Key Concepts section
  - [x] Remove this whole section (as a separate section). It's not interesting/engaging and is just doc (and I say that with love, as a docs writer). No one reads doc for the sake of it (we risk losing them at this point), they want to see it in context, especially in a guide. Also, by having the concepts listed up-front like that, we're expecting them to read and commit to memory before they can make sense of everything else further down (or keep scrolling back and forth to refer back). Instead, this info should be filtered more concisely into the relevant sections further down, introducing concepts gradually and building on what they've learnt previously. And the reader can just get on with the guide instead of yet more reading first.
- Building the Producer in the system microservice section
  - [x] Rename this heading to "Creating the Producer in the system microservice". The section is about creating it, not building it, which comes later (I know building/creating can be used interchangeably but we're using "building" further on to talk about Maven builds and Docker builds).
  - [x]  This section needs a bit more context and explanation so that the reader knows what's going on and why they're doing the actions they're asked to do, like this:
  >
  >Navigate to the `start` directory to begin.
  >
  >The `system` microservice is the producer of the messages that are published to the Kafka messaging system as a stream of events. The `system` microservice publishes an event every 15 seconds containing its calculation of the average system load (its CPU usage) for the last minute. [don't need to explain how that's calculated]
  >
  >(Action) Create the SystemService class.
  >
  >The SystemService class contains a Publisher method called `sendSystemLoad()` which calculates and returns the average system load. The `@Outgoing` annotation on the `sendSystemLoad()` method indicates that the method publishes its calculation as a message on a topic in the Kafka messaging system. The `Flowable.interval()` method from rxJava is used to set the frequency with which the `system` service  publishes the calculation to the event stream.
  >
  >The messages are transported between the service and the Kafka messaging system using a channel called `systemLoad`. The name of the channel to use is set in the `@Outgoing("systemLoad)` annotation. Later in the guide, you will configure the service so that any messages sent by the ` system` service through the `systemLoad` channel are published on a topic called `systemLoadTopic`, as shown in the following diagram:
  >
  >![publisher](https://user-images.githubusercontent.com/3322532/79475798-1215df00-8000-11ea-939c-4e02832e6a11.png)
  - [x] The reader should be asked to "create" the file, not to "replace" it. Replacing it doesn't make sense here and is confusing because the guide is about learning to write a simple reactive application, not about migrating/modifying an existing app in some way. It's also confusing that there's a load of code already in the file that isn't used. We should only provide files in the `start` directory if they aren't relevant to their learning to save the user from having to create everything (which is boring and pointless).
  - [x] The `models/SystemLoad.java` file is displayed without syntax highlighting, which doesn't look right. However, I don't think it's necessary to show this file in the guide at all, especially as it isn't mentioned in the guide. If the reader really cares, they can go look in the github repo for the file.
  - [x] Move the Maven pom file updates to the Building section. I know that might not be exactly the flow in which you would write the app in real-life but it keeps the conceptually similar steps together and leaves the building side of things till it's needed.
- Building the Consumer in the inventory microservice
  - [x] Rename the heading to "Creating the Consumer in the inventory microservice"
  - [x] This section needs more context and explanation so that the reader knows what's going on and why they're doing the actions they're asked to do, like this:
  >
  >The inventory microservice records in its inventory the average system load information that it has received from potentially multiple instances of the `system` service (though there is only one instance in this application for simplicity).
  >
  >(Action) Create the InventoryResource class. ["create" don't "replace" - it doesn't make sense and is confusing]
  >
  >The InventoryResource class contains a method called `updateStatus()` which receives the message containing the average system load and updates its existing inventory of systems and their average system load. The `@Incoming("systemLoad")` annotation on the `updateStatus()` method indicates that the method retrieves the average system load information by connecting to the channel called `systemLoad`. Later in the guide, you will configure the service so that any messages sent by the ` system` service through the `systemLoad` channel are retrieved from a topic called `systemLoadTopic`, as shown in the following diagram:
  > ![image](https://user-images.githubusercontent.com/3322532/79476740-49d15680-8001-11ea-90e8-a852f9f5820f.png)
  - [x] This diagram could have the producer part removed in this context. Or, maybe, the Outgoing bit could be greyed out so that the Incoming bit is more visible?
  - [x] The diagram text also needs to be slightly larger so it's clearer to read. The size of the diagram is fine, could cope with being a bit wider, but the text is a little too small.
  - [x] It should say "message broker" without the hyphen.
- Configuring the MicroProfile Reactive Messaging connectors section
  - [x] This needs an introduction, so re-draft as:
  >
  >The system and inventory services exchange messages with the external messaging system through a channel. The MicroProfile Reactive Messaging Connectors API makes it easy to connect each service to the channel. You just need to add some configuration keys in a properties file for each of the services to define properties such as the name of the channel and the topic in the Kafka messaging system.
  >
  >The system and inventory microservices each have a MicroProfile Config properties file to define the properties of their outgoing and incoming streams.
  >
  >(Action) Create the system/microprofile-config.properties file [I noticed there's a slash missing in the action box thing at the moment.]
  >
  >(only minor wording tweaks/corrections in this) The mp.messaging.connector.liberty-kafka.bootstrap.servers property configures the host name and port for connecting to the Kafka server. The system microservice uses an outgoing connector to send messages through the systemLoad channel to the systemLoadTopic topic in the Kafka message broker, so that the inventory microservices can consume the messages. The key.serializer and value.serializer properties characterize how to serialize the messages. The class SystemLoadSerializer implements the logic for turning a SystemLoad object into JSON and is configured as the value.serializer.
  - [x] "the Kafka connector." and "the Liberty Kafka connector" terms - do we need to mention this? It hasn't previously been explained - even in the original "Key Concepts" section, it's not clear why the user (a developer) needs to care about this? They just need to care that they can use the Connectors API to connect to Kafka - how Liberty does it doesn't really matter, does it? In the properties file, the heading comment `# Liberty Kafka connector` could instead say `# Kafka connection details` and be clearer what the details are for, rather than the mechanism used to make the connection. Then don't use the term "Kafka connector" at all.
  - [x] Then...
  >
  >The inventory microservices uses a similar microprofile-config.properties configuration to define its required incoming stream.
  >
  >(Action) Create the inventory..etc. (there's a missing slash in the draft guide here too)
  >
  >(moreorless as you have it, except for some minor edits similar to the system version) The inventory microservice uses an incoming connector to receive messages through the systemLoad channel which were published by the system microservice to the systemLoadTopic in the Kafka message broker. The key.deserializer and value.deserializer properties define how to deserialize the messages. The class SystemLoadDeserializer implements the logic for turning JSON into a SystemLoad object and is configured as the value.deserializer.
  >
  >The group.id defines a unique name for the consumer group. All these properties are required by the Apache Kafka Producer Configs and Apache Kafka Consumer Configs.
- Configuring the server section
  - [x] Needs more context to why you're doing this:
  >
  >To get the services running, the Liberty server on which each service will run needs to be correctly configured. The system service and the inventory service each need to have its relevant features enabled, including the MicroProfile Reactive Messaging (`mpReactiveMessaging-1.0`) and MicroProfile Config (`mpConfig-1.3`) features.
  >
  >(Action) Create the system/server.xml configuration file (there's a slash missing in the draft guide) (The action should be to "create" not "update" the server.xml. There's no reason in the context of this guide to be updating an existing server.xml.)
  >
  >The inventory microservice server.xml is already configured for you.
  - [x] Why is the mpHealth feature included in this app? It seems unnecessary complexity for this app. Can we remove it from this guide?
- Building the application section
  - [x] Rename this to "Building and running the application" as in the REST intro guide.
  - [ ] Start with a brief intro and then the bit about Maven removed from earlier:
  >
  >Build the system and inventory microservices using Maven and then run them in Docker containers.
  >
  >(Action) Create the Maven configuration file (have them "create" not "update" the Maven pom. Usually, it's not actually necessary to have them edit the pom at all in a guide, but I think you're right here that it's useful to show that there are reactive-specific bits that need to be present in the pom.xml.)
  >
  >The pom.xml lists the microprofile-reactive-messaging-api, kafka-clients, and rxjava dependencies.
  - [x] Then have the run maven/docker instructions as you've got them in the draft.
- Testing the application - looks good as it is.
- Tearing down the env - looks good as it is.
- Other style comments
  - [x] message broker should not be hyphenated
  - [x] Don't link to the specs. The spec is aimed at a different audience than this guide. We will have more doc that we can link to from this (and other guides) in future but we can live without that for now.
  - [x] Link to the MP Config guide somewhere appropriate (eg when the MP Config guide is mentioned?)
  - [ ] We should call the services "System service" and "Inventory service" (capitalised) or we should refer to them accurately as the "`SystemService` service" etc (though I prefer the former in most contexts). At the moment, the monospace higlighting implies that `system` and `inventory` are actual names of resources but I don't think they ever are?

**Comment by lauracowen** [comment]
Let me know when you're done, or if you have any questions, and I'll re-review as quickly as I can.

**Comment by gkwan-ibm** [comment]
@yeekangc

**Comment by ankitagrawa** [comment]
@lauracowen  : Feedback addressed.

**Comment by ankitagrawa** [comment]
Closing this issue since feedback has been addressed.
