### ISSUE TITLE
ID review feedback

### ISSUE THREAD

**Issue by Charlotte-Holt** [OpenLiberty/draft-guide-microprofile-reactive-messaging#75]
My feedback is included in the attached Word document. As always, read through my suggestions and make sure they make sense to you. Feel free to reach out to me with any questions. Thanks! 

[Creating reactive Java microservices-ID-feedback.docx](https://github.com/OpenLiberty/draft-guide-microprofile-reactive-messaging/files/4504550/Creating.reactive.Java.microservices-ID-feedback.docx)

**Comment by ankitagrawa** [comment]
feedback addressed @Charlotte-Holt @gkwan-ibm

**Comment by Charlotte-Holt** [comment]
ID review complete. Thanks!!
